"""
Transcript fetching using YouTube captions only.

Priority order:
  1. Manually created YouTube transcript (any language)
  2. Auto-generated YouTube transcript (any language)
  3. TRANSCRIPT UNAVAILABLE

No Whisper. No speech-to-text. No audio transcription.
No translation. Saves transcript text exactly as provided by YouTube.

Raises TranscriptBlocked when YouTube is rate-limiting or IP-blocking the
request. Callers must catch this to implement retry logic.
All other failures are treated as "transcript unavailable" and do NOT raise.
"""


class TranscriptBlocked(Exception):
    """
    Raised when YouTube blocks the transcript request via rate-limiting or
    IP blocking. Distinguished from a missing transcript so the caller can
    retry the same video after a delay, rather than moving on.
    """
    pass


def get_transcript(video_id):
    """
    Fetch transcript from YouTube captions using the public API only.

    Prefers manually created transcripts over auto-generated ones.
    Accepts any language — does not translate.

    Returns: (transcript_text, is_available)
      - transcript_text: full transcript string, or "TRANSCRIPT UNAVAILABLE"
      - is_available:    True if a real transcript was obtained

    Raises:
      TranscriptBlocked — YouTube is rate-limiting / IP-blocking. Caller
                          must wait and retry the SAME video.
    """
    try:
        from youtube_transcript_api import YouTubeTranscriptApi
        from youtube_transcript_api._errors import (
            IpBlocked,
            RequestBlocked,
            VideoUnavailable,
            NoTranscriptFound,
            TranscriptsDisabled,
            CouldNotRetrieveTranscript,
        )
    except ImportError:
        print("    [!] youtube-transcript-api not installed.")
        return "TRANSCRIPT UNAVAILABLE", False

    try:
        ytt_api = YouTubeTranscriptApi()
        transcript_list = ytt_api.list(video_id)

        # Separate manual vs generated by iterating the public iterator
        manual_transcripts = []
        generated_transcripts = []

        for t in transcript_list:
            if t.is_generated:
                generated_transcripts.append(t)
            else:
                manual_transcripts.append(t)

        # Pick the best available transcript
        transcript = None
        if manual_transcripts:
            transcript = manual_transcripts[0]
        elif generated_transcripts:
            transcript = generated_transcripts[0]

        if transcript is None:
            # No transcripts exist — this is a normal, non-blocked outcome
            return "TRANSCRIPT UNAVAILABLE", False

        # Fetch the actual transcript segments
        fetched = transcript.fetch()

        text_parts = []
        for segment in fetched:
            if isinstance(segment, dict):
                text = segment.get('text', '')
            else:
                text = getattr(segment, 'text', str(segment))
            text_parts.append(text)

        full_text = ' '.join(text_parts).strip()

        if full_text:
            return full_text, True

        return "TRANSCRIPT UNAVAILABLE", False

    except (IpBlocked, RequestBlocked) as e:
        # YouTube is blocking requests — caller must retry with a delay
        raise TranscriptBlocked(str(e)) from e

    except (NoTranscriptFound, TranscriptsDisabled, VideoUnavailable):
        # Legitimate "no transcript" cases — not a block
        return "TRANSCRIPT UNAVAILABLE", False

    except CouldNotRetrieveTranscript as e:
        err = str(e).lower()
        if "blocked" in err or "ip" in err:
            raise TranscriptBlocked(str(e)) from e
        return "TRANSCRIPT UNAVAILABLE", False

    except Exception as e:
        # Unknown error — treat as unavailable, do not raise
        print(f"    [!] Transcript error: {e}")
        return "TRANSCRIPT UNAVAILABLE", False
