"""
Transcript fetching using YouTube captions only.

Priority order:
  1. Manually created YouTube transcript (any language)
  2. Auto-generated YouTube transcript (any language)
  3. TRANSCRIPT UNAVAILABLE

No Whisper. No speech-to-text. No audio transcription.
No translation. Saves transcript text exactly as provided by YouTube.
"""


def fetch_youtube_transcript(video_id):
    """
    Fetch transcript from YouTube captions using public API only.

    Iterates the available transcript list via the public iterator.
    Prefers manually created transcripts over auto-generated ones.
    Accepts any language — does not translate.

    Returns transcript text or None if unavailable.
    """
    try:
        from youtube_transcript_api import YouTubeTranscriptApi
    except ImportError:
        print("    [!] youtube-transcript-api not installed.")
        return None

    try:
        ytt_api = YouTubeTranscriptApi()
        transcript_list = ytt_api.list(video_id)

        # Separate manual vs generated by iterating the public iterator
        manual_transcripts = []
        generated_transcripts = []

        for t in transcript_list:
            if t.is_generated:
                generated_transcripts.append(t)
            else:
                manual_transcripts.append(t)

        # Pick the best available transcript
        transcript = None
        if manual_transcripts:
            transcript = manual_transcripts[0]
        elif generated_transcripts:
            transcript = generated_transcripts[0]

        if transcript is None:
            return None

        # Fetch the actual transcript data
        fetched = transcript.fetch()

        text_parts = []
        for segment in fetched:
            if isinstance(segment, dict):
                text = segment.get('text', '')
            else:
                text = getattr(segment, 'text', str(segment))
            text_parts.append(text)

        full_text = ' '.join(text_parts).strip()
        return full_text if full_text else None

    except Exception as e:
        print(f"    [!] YouTube transcript fetch failed: {e}")
        return None


def get_transcript(video_id):
    """
    Main transcript fetching function.

    Tries YouTube captions only (manual then auto-generated, any language).
    If none available, returns "TRANSCRIPT UNAVAILABLE".

    Returns: (transcript_text, is_available)
      - transcript_text: the transcript string
      - is_available: True if a real transcript was obtained
    """
    transcript = fetch_youtube_transcript(video_id)
    if transcript:
        print("DONE")
        return transcript, True

    return "TRANSCRIPT UNAVAILABLE", False
